---
# Create custom logrotate config
nginx_logrotate_conf_enable: false
nginx_logrotate_conf:
  paths: /var/log/nginx/*.log # String or list of strings
    # - /var/log/nginx/*.log
  options: # daily # String or a list of strings
    - daily
    - missingok
    - rotate 14
    - compress
    - delaycompress
    - notifempty
    - create 0644 www-data adm # Changes NGINX log permissions
    - sharedscripts
