---
# Playbook for configuring Nginx as a load balancer for consul-template
- name: Configuring Nginx
  hosts: consul_template
  become: true
  become_user: root
  tasks:
    # - name: Getting backend name from consul KV storage
    #   set_fact:
    #     version: "{{ lookup('consul_kv', 'version', host='192.168.1.70 ') | default('v2', true) }}"
    # - name: Print version
    #   debug:
    #     msg: "version = {{ version }}"
    - name: Configure Nginx for consul-template
      include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_stream_template_enable: true
        nginx_config_stream_template:
          - template_file: stream/load-balancer.conf.tmp.j2
            conf_file_name: load-balancer.conf.tmp
            conf_file_location: /etc/nginx/conf.d
        nginx_config_cleanup: true
        nginx_config_cleanup_paths:
          - directory:
            - /etc/nginx/conf.d
            - /etc/nginx/sites-enabled
            recurse: false
        nginx_config_cleanup_files:
          - /etc/nginx/conf.d/default.conf
          - /etc/nginx/sites-enabled/000-default